name: Release app1

on:
  push:
    branches: 
      - main
    paths:
      - 'app1/**'
      - '.github/workflows/app1.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=songtianlun/dwk-app1
        # Set the platforms to build for here and thus reduce duplicating it.
        PLATFORMS=amd64,arm,arm64
        TAGS="${DOCKER_IMAGE}:${{ github.sha }},${DOCKER_IMAGE}:latest"

        # Set output parameters.

        if [ "${{github.event_name}}" == "pull_request" ]; then
          echo "push=false" >> $GITHUB_OUTPUT
        else
          echo "push=true" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT
        fi
        echo ::set-output name=platforms::${PLATFORMS}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ steps.prep.outputs.platforms }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:latest

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: app1
        platforms: ${{ steps.prep.outputs.platforms }}
        push: ${{ steps.prep.outputs.push }}
        tags: ${{ steps.prep.outputs.tags }}
